# Generated by Django 4.2.13 on 2024-06-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO api_offergroup (id, name) VALUES (0, 'Ile-de-France');"
        ),
        migrations.AlterField(
            model_name='offer',
            name='lu',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('offer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='api.offergroup')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.offergroup'),
            preserve_default=False,
        ),
    ]
